-- Auto-generated from lib/combinations.ts — all 310 hardcoded recipes
-- Run this in your Supabase SQL editor (self-contained)

create table if not exists public.combinations (
  combo_key text primary key,
  result text not null,
  emoji text not null
);

alter table public.combinations enable row level security;

drop policy if exists "allow_read_combinations" on public.combinations;
drop policy if exists "allow_insert_combinations" on public.combinations;
drop policy if exists "allow_update_combinations" on public.combinations;

create policy "allow_read_combinations" on public.combinations for select using (true);
create policy "allow_insert_combinations" on public.combinations for insert with check (true);
create policy "allow_update_combinations" on public.combinations for update using (true);

insert into public.combinations (combo_key, result, emoji) values
('fire+water', 'Steam', '♨️'),
('earth+fire', 'Lava', '🌋'),
('fire+wind', 'Smoke', '🌫️'),
('earth+water', 'Mud', '🟤'),
('water+wind', 'Wave', '🌊'),
('earth+wind', 'Dust', '🌪️'),
('fire+steam', 'Engine', '⚙️'),
('steam+water', 'Rain', '🌧️'),
('earth+steam', 'Geyser', '♨️'),
('steam+wind', 'Cloud', '☁️'),
('steam+steam', 'Fog', '🌁'),
('lava+water', 'Stone', '🪨'),
('earth+lava', 'Volcano', '🌋'),
('lava+wind', 'Ash', '⬛'),
('fire+lava', 'Magma', '🔴'),
('lava+lava', 'Mountain', '⛰️'),
('fire+smoke', 'Wildfire', '🔥'),
('smoke+water', 'Fog', '🌁'),
('earth+smoke', 'Soot', '⬛'),
('smoke+wind', 'Smog', '🌁'),
('fire+mud', 'Brick', '🧱'),
('mud+water', 'Swamp', '🌿'),
('earth+mud', 'Clay', '🏺'),
('mud+wind', 'Dust Storm', '🌪️'),
('mud+mud', 'Quicksand', '⏳'),
('earth+wave', 'Beach', '🏖️'),
('wave+wind', 'Storm', '⛈️'),
('wave+wave', 'Ocean', '🌊'),
('dust+fire', 'Explosion', '💥'),
('dust+earth', 'Desert', '🏜️'),
('dust+wind', 'Sandstorm', '🌪️'),
('dust+dust', 'Sand', '🏜️'),
('dust+water', 'Mud', '🟤'),
('engine+fire', 'Car', '🚗'),
('engine+water', 'Submarine', '🚢'),
('earth+engine', 'Train', '🚂'),
('engine+wind', 'Airplane', '✈️'),
('engine+steam', 'Locomotive', '🚂'),
('engine+engine', 'Factory', '🏭'),
('earth+rain', 'Flower', '🌸'),
('fire+rain', 'Rainbow', '🌈'),
('rain+wind', 'Typhoon', '🌀'),
('rain+rain', 'Flood', '🌊'),
('cloud+rain', 'Storm', '⛈️'),
('cloud+fire', 'Lightning', '⚡'),
('cloud+water', 'Rain', '🌧️'),
('cloud+wind', 'Hurricane', '🌀'),
('earth+cloud', 'Fog', '🌁'),
('cloud+cloud', 'Thunderstorm', '⛈️'),
('stone+fire', 'Metal', '⚙️'),
('stone+water', 'Pebble', '🪨'),
('earth+stone', 'Mountain', '⛰️'),
('stone+wind', 'Sand', '🏜️'),
('stone+stone', 'Boulder', '🪨'),
('volcano+fire', 'Eruption', '🌋'),
('volcano+water', 'Island', '🏝️'),
('earth+volcano', 'Landscape', '🌄'),
('ash+fire', 'Phoenix', '🦅'),
('ash+earth', 'Soil', '🌱'),
('ash+wind', 'Dust', '🌪️'),
('brick+earth', 'House', '🏠'),
('brick+brick', 'Wall', '🧱'),
('brick+water', 'Cement', '🏗️'),
('brick+fire', 'Furnace', '🔥'),
('earth+swamp', 'Marsh', '🌾'),
('swamp+fire', 'Bog', '🌿'),
('clay+fire', 'Pottery', '🏺'),
('clay+water', 'Sculpture', '🗿'),
('beach+fire', 'Bonfire', '🔥'),
('beach+water', 'Coast', '🌊'),
('beach+wind', 'Dune', '🏜️'),
('storm+fire', 'Thunder', '⛈️'),
('earth+storm', 'Earthquake', '🌍'),
('storm+wind', 'Hurricane', '🌀'),
('storm+water', 'Flood', '🌊'),
('storm+storm', 'Apocalypse', '💀'),
('desert+fire', 'Mirage', '🌅'),
('desert+water', 'Oasis', '🌴'),
('desert+wind', 'Sandstorm', '🌪️'),
('metal+fire', 'Forge', '⚒️'),
('metal+water', 'Rust', '🟤'),
('earth+metal', 'Ore', '⛏️'),
('metal+wind', 'Bell', '🔔'),
('metal+metal', 'Steel', '🔩'),
('metal+stone', 'Sword', '⚔️'),
('mountain+water', 'Lake', '🏞️'),
('mountain+wind', 'Avalanche', '❄️'),
('mountain+stone', 'Cliff', '🏔️'),
('mountain+fire', 'Volcano', '🌋'),
('mountain+mountain', 'Himalayas', '🏔️'),
('ocean+fire', 'Coral', '🪸'),
('earth+ocean', 'Island', '🏝️'),
('ocean+wind', 'Current', '🌊'),
('ocean+water', 'Sea', '🌊'),
('ocean+ocean', 'World', '🌍'),
('fire+sand', 'Glass', '🪟'),
('sand+water', 'Quicksand', '⏳'),
('earth+sand', 'Desert', '🏜️'),
('sand+wind', 'Dune', '🏜️'),
('sand+sand', 'Hourglass', '⌛'),
('lightning+fire', 'Thunderbolt', '⚡'),
('lightning+metal', 'Magnet', '🧲'),
('lightning+lightning', 'Electricity', '⚡'),
('steel+fire', 'Crucible', '⚗️'),
('earth+steel', 'Railroad', '🛤️'),
('steel+stone', 'Armor', '🛡️'),
('steel+metal', 'Alloy', '⚙️'),
('fire+glass', 'Lens', '🔍'),
('glass+water', 'Aquarium', '🐠'),
('earth+glass', 'Window', '🪟'),
('glass+wind', 'Crystal', '💎'),
('glass+glass', 'Mirror', '🪞'),
('glass+metal', 'Telescope', '🔭'),
('electricity+fire', 'Plasma', '🌟'),
('electricity+water', 'Battery', '🔋'),
('earth+electricity', 'Circuit', '💡'),
('electricity+wind', 'Generator', '⚡'),
('electricity+metal', 'Wire', '🔌'),
('electricity+glass', 'Light Bulb', '💡'),
('electricity+electricity', 'Lightning', '⚡'),
('earth+flower', 'Field', '🌾'),
('flower+wind', 'Pollen', '🌸'),
('flower+flower', 'Bouquet', '💐'),
('flower+water', 'Garden', '🌷'),
('fire+rainbow', 'Spectrum', '🌈'),
('flood+wind', 'Hurricane', '🌀'),
('flood+flood', 'Deluge', '🌊'),
('earthquake+water', 'Tsunami', '🌊'),
('earthquake+wind', 'Tornado', '🌪️'),
('forge+fire', 'Sword', '⚔️'),
('forge+metal', 'Anvil', '⚒️'),
('earth+garden', 'Farm', '🌾'),
('garden+water', 'Jungle', '🌿'),
('garden+wind', 'Scarecrow', '🌾'),
('farm+wind', 'Windmill', '🌬️'),
('farm+water', 'Rice Field', '🌾'),
('soil+water', 'Life', '🌱'),
('life+fire', 'Animal', '🦁'),
('life+water', 'Fish', '🐟'),
('earth+life', 'Plant', '🌿'),
('life+wind', 'Bird', '🦅'),
('life+life', 'Evolution', '🧬'),
('plant+water', 'Tree', '🌲'),
('earth+plant', 'Forest', '🌲'),
('plant+wind', 'Seed', '🌱'),
('plant+plant', 'Garden', '🌷'),
('plant+fire', 'Charcoal', '⬛'),
('tree+fire', 'Torch', '🔦'),
('tree+wind', 'Paper', '📄'),
('tree+tree', 'Forest', '🌲'),
('tree+metal', 'Axe', '🪓'),
('forest+fire', 'Wildfire', '🔥'),
('forest+water', 'Rainforest', '🌿'),
('earth+forest', 'Jungle', '🌿'),
('fish+ocean', 'Whale', '🐋'),
('fish+fish', 'School', '🐟'),
('animal+wind', 'Bird', '🦅'),
('animal+animal', 'Herd', '🦌'),
('bird+fire', 'Phoenix', '🔥'),
('bird+water', 'Duck', '🦆'),
('bird+wind', 'Eagle', '🦅'),
('bird+bird', 'Flock', '🦅'),
('evolution+fire', 'Human', '🧑'),
('human+fire', 'Cook', '👨‍🍳'),
('human+water', 'Swimmer', '🏊'),
('earth+human', 'Farmer', '👨‍🌾'),
('human+wind', 'Sailor', '⛵'),
('human+human', 'Society', '🏙️'),
('human+metal', 'Knight', '⚔️'),
('human+electricity', 'Cyborg', '🤖'),
('house+earth', 'Village', '🏘️'),
('house+house', 'City', '🏙️'),
('house+stone', 'Castle', '🏰'),
('house+fire', 'Ashes', '🔥'),
('castle+earth', 'Kingdom', '👑'),
('crystal+lightning', 'Magic', '✨'),
('magic+fire', 'Fireball', '🔥'),
('magic+water', 'Potion', '⚗️'),
('magic+lightning', 'Wizard', '🧙'),
('magic+human', 'Mage', '🧙'),
('magic+stone', 'Rune', '🔮'),
('magic+darkness', 'Dark Magic', '🌑'),
('wizard+fire', 'Pyromancer', '🔥'),
('wizard+wizard', 'Archmage', '🧙‍♂️'),
('dragon+fire', 'Dragon Fire', '🐲'),
('dragon+water', 'Sea Dragon', '🐉'),
('dragon+human', 'Dragon Rider', '🐉'),
('dragon+magic', 'Ancient Dragon', '🐲'),
('star+fire', 'Supernova', '💥'),
('star+water', 'Nebula', '🌌'),
('star+wind', 'Comet', '☄️'),
('star+star', 'Galaxy', '🌌'),
('star+stone', 'Asteroid', '☄️'),
('sun+fire', 'Solar Flare', '☀️'),
('sun+water', 'Rainbow', '🌈'),
('earth+sun', 'Day', '☀️'),
('sun+moon', 'Eclipse', '🌑'),
('moon+water', 'Tide', '🌊'),
('earth+moon', 'Night', '🌙'),
('moon+wind', 'Werewolf', '🐺'),
('moon+star', 'Crescent', '🌙'),
('planet+fire', 'Mars', '🔴'),
('planet+water', 'Neptune', '🔵'),
('planet+wind', 'Gas Giant', '🪐'),
('planet+star', 'Solar System', '🌌'),
('planet+planet', 'Universe', '🌌'),
('galaxy+fire', 'Black Hole', '🌑'),
('galaxy+galaxy', 'Multiverse', '🌌'),
('car+electricity', 'Electric Car', '🔋'),
('car+car', 'Traffic', '🚗'),
('rocket+star', 'Spacecraft', '🛸'),
('rocket+planet', 'Space Exploration', '🌌'),
('robot+electricity', 'AI', '🤖'),
('robot+human', 'Cyborg', '🦾'),
('robot+robot', 'Robot Army', '🤖'),
('computer+electricity', 'Supercomputer', '💻'),
('computer+robot', 'AI', '🤖'),
('computer+human', 'Programmer', '👨‍💻'),
('crystal+water', 'Ice', '❄️'),
('ice+fire', 'Water', '💧'),
('ice+water', 'Iceberg', '🧊'),
('earth+ice', 'Glacier', '🏔️'),
('ice+wind', 'Blizzard', '❄️'),
('ice+ice', 'Tundra', '🏔️'),
('snow+fire', 'Slush', '💧'),
('snow+water', 'Ice', '❄️'),
('snow+wind', 'Blizzard', '❄️'),
('snow+snow', 'Snowstorm', '🌨️'),
('atom+fire', 'Fusion', '⚡'),
('atom+atom', 'Molecule', '⚗️'),
('atom+electricity', 'Electron', '⚡'),
('molecule+molecule', 'Protein', '🧬'),
('dna+fire', 'Mutation', '🧬'),
('dna+water', 'Cell', '🦠'),
('dna+dna', 'Clone', '🧑'),
('dna+human', 'Genetics', '🧬'),
('dna+evolution', 'Species', '🦕'),
('fossil+life', 'Dinosaur', '🦕'),
('dinosaur+fire', 'Dragon', '🐉'),
('oil+fire', 'Explosion', '💥'),
('gold+metal', 'Crown', '👑'),
('gold+human', 'King', '👑'),
('diamond+fire', 'Brilliant', '💎'),
('diamond+metal', 'Drill', '⛏️'),
('time+fire', 'Eternity', '♾️'),
('earth+time', 'History', '📜'),
('time+human', 'Philosopher', '🤔'),
('time+stone', 'Fossil', '🦕'),
('time+life', 'Death', '💀'),
('time+time', 'Infinity', '♾️'),
('darkness+fire', 'Shadow', '🌑'),
('darkness+earth', 'Cave', '🕳️'),
('darkness+human', 'Shadow', '👤'),
('light+darkness', 'Balance', '☯️'),
('earth+light', 'Dawn', '🌅'),
('light+human', 'Enlightenment', '✨'),
('river+earth', 'Canyon', '🏜️'),
('river+stone', 'Waterfall', '💧'),
('river+mountain', 'Waterfall', '💧'),
('music+fire', 'Rock', '🎸'),
('music+wind', 'Flute', '🎶'),
('music+lightning', 'Electric Guitar', '🎸'),
('music+magic', 'Spell Song', '🎵'),
('death+fire', 'Hell', '😈'),
('death+water', 'River Styx', '🌊'),
('death+wind', 'Ghost', '👻'),
('death+human', 'Undead', '🧟'),
('death+magic', 'Necromancy', '💀'),
('death+life', 'Rebirth', '✨'),
('ghost+fire', 'Will-o-Wisp', '👻'),
('ghost+human', 'Haunting', '👻'),
('ghost+magic', 'Exorcism', '✝️'),
('wolf+moon', 'Werewolf', '🌕'),
('wolf+wolf', 'Pack', '🐺'),
('whale+fire', 'Leviathan', '🐋'),
('shark+magic', 'Megalodon', '🦈'),
('smoke+cloud', 'Pollution', '🌁'),
('pollution+rain', 'Acid Rain', '☔'),
('mushroom+magic', 'Fairy Ring', '🍄'),
('mushroom+life', 'Mycelium', '🍄'),
('sword+fire', 'Flaming Sword', '⚔️'),
('sword+magic', 'Enchanted Blade', '⚔️'),
('sword+ice', 'Ice Sword', '❄️'),
('armor+magic', 'Enchanted Armor', '🛡️'),
('society+fire', 'Revolution', '🔥'),
('earth+society', 'Civilization', '🏛️'),
('society+metal', 'Industrial Revolution', '🏭'),
('civilization+fire', 'War', '⚔️'),
('earth+civilization', 'History', '📜'),
('civilization+metal', 'Industrialization', '🏭'),
('civilization+magic', 'Mythology', '📜'),
('potion+life', 'Elixir', '⚗️'),
('potion+death', 'Poison', '☠️'),
('magnet+metal', 'Electric Motor', '⚙️'),
('magnet+water', 'Compass', '🧭'),
('lens+glass', 'Microscope', '🔬'),
('telescope+star', 'Astronomy', '🔭'),
('phoenix+fire', 'Immortality', '✨'),
('phoenix+water', 'Mist', '🌫️'),
('earth+fossil', 'Archaeology', '🦴'),
('fossil+fire', 'Oil', '🛢️'),
('lightning+sword', 'Thunder Blade', '⚡⚔️'),
('ash+sword', 'Shadow Blade', '🌑⚔️'),
('magic+sword', 'Holy Sword', '✨⚔️'),
('dragon+sword', 'Dragon Slayer', '🐉⚔️'),
('ash+charcoal', 'Gunpowder', '💥'),
('gunpowder+metal', 'Gun', '🔫'),
('gun+telescope', 'Sniper Rifle', '🎯'),
('gun+magic', 'Magic Gun', '✨🔫'),
('metal+shield', 'Steel Shield', '🛡️')
on conflict (combo_key) do update set result = excluded.result, emoji = excluded.emoji;
