export interface Element {
  name: string;
  emoji: string;
  isNew?: boolean;
}

export const BASE_ELEMENTS: Element[] = [
  { name: 'Fire', emoji: '🔥' },
  { name: 'Water', emoji: '💧' },
  { name: 'Earth', emoji: '🌍' },
  { name: 'Wind', emoji: '💨' },
];

export function makeKey(a: string, b: string): string {
  return [a.toLowerCase(), b.toLowerCase()].sort().join('+');
}

export const COMBINATIONS: Record<string, { result: string; emoji: string }> = {
  // Base
  'fire+water': { result: 'Steam', emoji: '♨️' },
  'earth+fire': { result: 'Lava', emoji: '🌋' },
  'fire+wind': { result: 'Smoke', emoji: '🌫️' },
  'earth+water': { result: 'Mud', emoji: '🟤' },
  'water+wind': { result: 'Wave', emoji: '🌊' },
  'earth+wind': { result: 'Dust', emoji: '🌪️' },
  // Layer 2
  'fire+steam': { result: 'Engine', emoji: '⚙️' },
  'steam+water': { result: 'Rain', emoji: '🌧️' },
  'earth+steam': { result: 'Geyser', emoji: '♨️' },
  'steam+wind': { result: 'Cloud', emoji: '☁️' },
  'steam+steam': { result: 'Fog', emoji: '🌁' },
  'lava+water': { result: 'Stone', emoji: '🪨' },
  'earth+lava': { result: 'Volcano', emoji: '🌋' },
  'lava+wind': { result: 'Ash', emoji: '⬛' },
  'fire+lava': { result: 'Magma', emoji: '🔴' },
  'lava+lava': { result: 'Mountain', emoji: '⛰️' },
  'fire+smoke': { result: 'Wildfire', emoji: '🔥' },
  'smoke+water': { result: 'Fog', emoji: '🌁' },
  'earth+smoke': { result: 'Soot', emoji: '⬛' },
  'smoke+wind': { result: 'Smog', emoji: '🌁' },
  'fire+mud': { result: 'Brick', emoji: '🧱' },
  'mud+water': { result: 'Swamp', emoji: '🌿' },
  'earth+mud': { result: 'Clay', emoji: '🏺' },
  'mud+wind': { result: 'Dust Storm', emoji: '🌪️' },
  'mud+mud': { result: 'Quicksand', emoji: '⏳' },
  'earth+wave': { result: 'Beach', emoji: '🏖️' },
  'wave+wind': { result: 'Storm', emoji: '⛈️' },
  'wave+wave': { result: 'Ocean', emoji: '🌊' },
  'dust+fire': { result: 'Explosion', emoji: '💥' },
  'dust+earth': { result: 'Desert', emoji: '🏜️' },
  'dust+wind': { result: 'Sandstorm', emoji: '🌪️' },
  'dust+dust': { result: 'Sand', emoji: '🏜️' },
  'dust+water': { result: 'Mud', emoji: '🟤' },
  // Layer 3
  'engine+fire': { result: 'Car', emoji: '🚗' },
  'engine+water': { result: 'Submarine', emoji: '🚢' },
  'earth+engine': { result: 'Train', emoji: '🚂' },
  'engine+wind': { result: 'Airplane', emoji: '✈️' },
  'engine+steam': { result: 'Locomotive', emoji: '🚂' },
  'engine+engine': { result: 'Factory', emoji: '🏭' },
  'earth+rain': { result: 'Flower', emoji: '🌸' },
  'fire+rain': { result: 'Rainbow', emoji: '🌈' },
  'rain+wind': { result: 'Typhoon', emoji: '🌀' },
  'rain+rain': { result: 'Flood', emoji: '🌊' },
  'cloud+rain': { result: 'Storm', emoji: '⛈️' },
  'cloud+fire': { result: 'Lightning', emoji: '⚡' },
  'cloud+water': { result: 'Rain', emoji: '🌧️' },
  'cloud+wind': { result: 'Hurricane', emoji: '🌀' },
  'earth+cloud': { result: 'Fog', emoji: '🌁' },
  'cloud+cloud': { result: 'Thunderstorm', emoji: '⛈️' },
  'stone+fire': { result: 'Metal', emoji: '⚙️' },
  'stone+water': { result: 'Pebble', emoji: '🪨' },
  'earth+stone': { result: 'Mountain', emoji: '⛰️' },
  'stone+wind': { result: 'Sand', emoji: '🏜️' },
  'stone+stone': { result: 'Boulder', emoji: '🪨' },
  'volcano+fire': { result: 'Eruption', emoji: '🌋' },
  'volcano+water': { result: 'Island', emoji: '🏝️' },
  'earth+volcano': { result: 'Landscape', emoji: '🌄' },
  'ash+fire': { result: 'Phoenix', emoji: '🦅' },
  'ash+earth': { result: 'Soil', emoji: '🌱' },
  'ash+wind': { result: 'Dust', emoji: '🌪️' },
  'brick+earth': { result: 'House', emoji: '🏠' },
  'brick+brick': { result: 'Wall', emoji: '🧱' },
  'brick+water': { result: 'Cement', emoji: '🏗️' },
  'brick+fire': { result: 'Furnace', emoji: '🔥' },
  'earth+swamp': { result: 'Marsh', emoji: '🌾' },
  'swamp+fire': { result: 'Bog', emoji: '🌿' },
  'clay+fire': { result: 'Pottery', emoji: '🏺' },
  'clay+water': { result: 'Sculpture', emoji: '🗿' },
  'beach+fire': { result: 'Bonfire', emoji: '🔥' },
  'beach+water': { result: 'Coast', emoji: '🌊' },
  'beach+wind': { result: 'Dune', emoji: '🏜️' },
  'storm+fire': { result: 'Thunder', emoji: '⛈️' },
  'earth+storm': { result: 'Earthquake', emoji: '🌍' },
  'storm+wind': { result: 'Hurricane', emoji: '🌀' },
  'storm+water': { result: 'Flood', emoji: '🌊' },
  'storm+storm': { result: 'Apocalypse', emoji: '💀' },
  'desert+fire': { result: 'Mirage', emoji: '🌅' },
  'desert+water': { result: 'Oasis', emoji: '🌴' },
  'desert+wind': { result: 'Sandstorm', emoji: '🌪️' },
  'metal+fire': { result: 'Forge', emoji: '⚒️' },
  'metal+water': { result: 'Rust', emoji: '🟤' },
  'earth+metal': { result: 'Ore', emoji: '⛏️' },
  'metal+wind': { result: 'Bell', emoji: '🔔' },
  'metal+metal': { result: 'Steel', emoji: '🔩' },
  'metal+stone': { result: 'Sword', emoji: '⚔️' },
  'mountain+water': { result: 'Lake', emoji: '🏞️' },
  'mountain+wind': { result: 'Avalanche', emoji: '❄️' },
  'mountain+stone': { result: 'Cliff', emoji: '🏔️' },
  'mountain+fire': { result: 'Volcano', emoji: '🌋' },
  'mountain+mountain': { result: 'Himalayas', emoji: '🏔️' },
  'ocean+fire': { result: 'Coral', emoji: '🪸' },
  'earth+ocean': { result: 'Island', emoji: '🏝️' },
  'ocean+wind': { result: 'Current', emoji: '🌊' },
  'ocean+water': { result: 'Sea', emoji: '🌊' },
  'ocean+ocean': { result: 'World', emoji: '🌍' },
  'fire+sand': { result: 'Glass', emoji: '🪟' },
  'sand+water': { result: 'Quicksand', emoji: '⏳' },
  'earth+sand': { result: 'Desert', emoji: '🏜️' },
  'sand+wind': { result: 'Dune', emoji: '🏜️' },
  'sand+sand': { result: 'Hourglass', emoji: '⌛' },
  'lightning+fire': { result: 'Thunderbolt', emoji: '⚡' },
  'lightning+metal': { result: 'Magnet', emoji: '🧲' },
  'lightning+lightning': { result: 'Electricity', emoji: '⚡' },
  'steel+fire': { result: 'Crucible', emoji: '⚗️' },
  'earth+steel': { result: 'Railroad', emoji: '🛤️' },
  'steel+stone': { result: 'Armor', emoji: '🛡️' },
  'steel+metal': { result: 'Alloy', emoji: '⚙️' },
  'fire+glass': { result: 'Lens', emoji: '🔍' },
  'glass+water': { result: 'Aquarium', emoji: '🐠' },
  'earth+glass': { result: 'Window', emoji: '🪟' },
  'glass+wind': { result: 'Crystal', emoji: '💎' },
  'glass+glass': { result: 'Mirror', emoji: '🪞' },
  'glass+metal': { result: 'Telescope', emoji: '🔭' },
  'electricity+fire': { result: 'Plasma', emoji: '🌟' },
  'electricity+water': { result: 'Battery', emoji: '🔋' },
  'earth+electricity': { result: 'Circuit', emoji: '💡' },
  'electricity+wind': { result: 'Generator', emoji: '⚡' },
  'electricity+metal': { result: 'Wire', emoji: '🔌' },
  'electricity+glass': { result: 'Light Bulb', emoji: '💡' },
  'electricity+electricity': { result: 'Lightning', emoji: '⚡' },
  'earth+flower': { result: 'Field', emoji: '🌾' },
  'flower+wind': { result: 'Pollen', emoji: '🌸' },
  'flower+flower': { result: 'Bouquet', emoji: '💐' },
  'flower+water': { result: 'Garden', emoji: '🌷' },
  'fire+rainbow': { result: 'Spectrum', emoji: '🌈' },
  'flood+wind': { result: 'Hurricane', emoji: '🌀' },
  'flood+flood': { result: 'Deluge', emoji: '🌊' },
  'earthquake+water': { result: 'Tsunami', emoji: '🌊' },
  'earthquake+wind': { result: 'Tornado', emoji: '🌪️' },
  'forge+fire': { result: 'Sword', emoji: '⚔️' },
  'forge+metal': { result: 'Anvil', emoji: '⚒️' },
  'earth+garden': { result: 'Farm', emoji: '🌾' },
  'garden+water': { result: 'Jungle', emoji: '🌿' },
  'garden+wind': { result: 'Scarecrow', emoji: '🌾' },
  'farm+wind': { result: 'Windmill', emoji: '🌬️' },
  'farm+water': { result: 'Rice Field', emoji: '🌾' },
  // Life
  'soil+water': { result: 'Life', emoji: '🌱' },
  'life+fire': { result: 'Animal', emoji: '🦁' },
  'life+water': { result: 'Fish', emoji: '🐟' },
  'earth+life': { result: 'Plant', emoji: '🌿' },
  'life+wind': { result: 'Bird', emoji: '🦅' },
  'life+life': { result: 'Evolution', emoji: '🧬' },
  'plant+water': { result: 'Tree', emoji: '🌲' },
  'earth+plant': { result: 'Forest', emoji: '🌲' },
  'plant+wind': { result: 'Seed', emoji: '🌱' },
  'plant+plant': { result: 'Garden', emoji: '🌷' },
  'plant+fire': { result: 'Charcoal', emoji: '⬛' },
  'tree+fire': { result: 'Torch', emoji: '🔦' },
  'tree+wind': { result: 'Paper', emoji: '📄' },
  'tree+tree': { result: 'Forest', emoji: '🌲' },
  'tree+metal': { result: 'Axe', emoji: '🪓' },
  'forest+fire': { result: 'Wildfire', emoji: '🔥' },
  'forest+water': { result: 'Rainforest', emoji: '🌿' },
  'earth+forest': { result: 'Jungle', emoji: '🌿' },
  'fish+ocean': { result: 'Whale', emoji: '🐋' },
  'fish+fish': { result: 'School', emoji: '🐟' },
  'animal+wind': { result: 'Bird', emoji: '🦅' },
  'animal+animal': { result: 'Herd', emoji: '🦌' },
  'bird+fire': { result: 'Phoenix', emoji: '🔥' },
  'bird+water': { result: 'Duck', emoji: '🦆' },
  'bird+wind': { result: 'Eagle', emoji: '🦅' },
  'bird+bird': { result: 'Flock', emoji: '🦅' },
  // Human
  'evolution+fire': { result: 'Human', emoji: '🧑' },
  'human+fire': { result: 'Cook', emoji: '👨‍🍳' },
  'human+water': { result: 'Swimmer', emoji: '🏊' },
  'earth+human': { result: 'Farmer', emoji: '👨‍🌾' },
  'human+wind': { result: 'Sailor', emoji: '⛵' },
  'human+human': { result: 'Society', emoji: '🏙️' },
  'human+metal': { result: 'Knight', emoji: '⚔️' },
  'human+electricity': { result: 'Cyborg', emoji: '🤖' },
  'house+earth': { result: 'Village', emoji: '🏘️' },
  'house+house': { result: 'City', emoji: '🏙️' },
  'house+stone': { result: 'Castle', emoji: '🏰' },
  'house+fire': { result: 'Ashes', emoji: '🔥' },
  'castle+earth': { result: 'Kingdom', emoji: '👑' },
  // Magic
  'crystal+lightning': { result: 'Magic', emoji: '✨' },
  'magic+fire': { result: 'Fireball', emoji: '🔥' },
  'magic+water': { result: 'Potion', emoji: '⚗️' },
  'magic+lightning': { result: 'Wizard', emoji: '🧙' },
  'magic+human': { result: 'Mage', emoji: '🧙' },
  'magic+stone': { result: 'Rune', emoji: '🔮' },
  'magic+darkness': { result: 'Dark Magic', emoji: '🌑' },
  'wizard+fire': { result: 'Pyromancer', emoji: '🔥' },
  'wizard+wizard': { result: 'Archmage', emoji: '🧙‍♂️' },
  'dragon+fire': { result: 'Dragon Fire', emoji: '🐲' },
  'dragon+water': { result: 'Sea Dragon', emoji: '🐉' },
  'dragon+human': { result: 'Dragon Rider', emoji: '🐉' },
  'dragon+magic': { result: 'Ancient Dragon', emoji: '🐲' },
  // Space
  'star+fire': { result: 'Supernova', emoji: '💥' },
  'star+water': { result: 'Nebula', emoji: '🌌' },
  'star+wind': { result: 'Comet', emoji: '☄️' },
  'star+star': { result: 'Galaxy', emoji: '🌌' },
  'star+stone': { result: 'Asteroid', emoji: '☄️' },
  'sun+fire': { result: 'Solar Flare', emoji: '☀️' },
  'sun+water': { result: 'Rainbow', emoji: '🌈' },
  'earth+sun': { result: 'Day', emoji: '☀️' },
  'sun+moon': { result: 'Eclipse', emoji: '🌑' },
  'moon+water': { result: 'Tide', emoji: '🌊' },
  'earth+moon': { result: 'Night', emoji: '🌙' },
  'moon+wind': { result: 'Werewolf', emoji: '🐺' },
  'moon+star': { result: 'Crescent', emoji: '🌙' },
  'planet+fire': { result: 'Mars', emoji: '🔴' },
  'planet+water': { result: 'Neptune', emoji: '🔵' },
  'planet+wind': { result: 'Gas Giant', emoji: '🪐' },
  'planet+star': { result: 'Solar System', emoji: '🌌' },
  'planet+planet': { result: 'Universe', emoji: '🌌' },
  'galaxy+fire': { result: 'Black Hole', emoji: '🌑' },
  'galaxy+galaxy': { result: 'Multiverse', emoji: '🌌' },
  // Tech
  'car+electricity': { result: 'Electric Car', emoji: '🔋' },
  'car+car': { result: 'Traffic', emoji: '🚗' },
  'rocket+star': { result: 'Spacecraft', emoji: '🛸' },
  'rocket+planet': { result: 'Space Exploration', emoji: '🌌' },
  'robot+electricity': { result: 'AI', emoji: '🤖' },
  'robot+human': { result: 'Cyborg', emoji: '🦾' },
  'robot+robot': { result: 'Robot Army', emoji: '🤖' },
  'computer+electricity': { result: 'Supercomputer', emoji: '💻' },
  'computer+robot': { result: 'AI', emoji: '🤖' },
  'computer+human': { result: 'Programmer', emoji: '👨‍💻' },
  // Ice
  'crystal+water': { result: 'Ice', emoji: '❄️' },
  'ice+fire': { result: 'Water', emoji: '💧' },
  'ice+water': { result: 'Iceberg', emoji: '🧊' },
  'earth+ice': { result: 'Glacier', emoji: '🏔️' },
  'ice+wind': { result: 'Blizzard', emoji: '❄️' },
  'ice+ice': { result: 'Tundra', emoji: '🏔️' },
  'snow+fire': { result: 'Slush', emoji: '💧' },
  'snow+water': { result: 'Ice', emoji: '❄️' },
  'snow+wind': { result: 'Blizzard', emoji: '❄️' },
  'snow+snow': { result: 'Snowstorm', emoji: '🌨️' },
  // Science
  'atom+fire': { result: 'Fusion', emoji: '⚡' },
  'atom+atom': { result: 'Molecule', emoji: '⚗️' },
  'atom+electricity': { result: 'Electron', emoji: '⚡' },
  'molecule+molecule': { result: 'Protein', emoji: '🧬' },
  'dna+fire': { result: 'Mutation', emoji: '🧬' },
  'dna+water': { result: 'Cell', emoji: '🦠' },
  'dna+dna': { result: 'Clone', emoji: '🧑' },
  'dna+human': { result: 'Genetics', emoji: '🧬' },
  'dna+evolution': { result: 'Species', emoji: '🦕' },
  // Misc
  'fossil+life': { result: 'Dinosaur', emoji: '🦕' },
  'dinosaur+fire': { result: 'Dragon', emoji: '🐉' },
  'oil+fire': { result: 'Explosion', emoji: '💥' },
  'gold+metal': { result: 'Crown', emoji: '👑' },
  'gold+human': { result: 'King', emoji: '👑' },
  'gold+magic': { result: "Philosopher's Stone", emoji: '🔮' },
  'diamond+fire': { result: 'Brilliant', emoji: '💎' },
  'diamond+metal': { result: 'Drill', emoji: '⛏️' },
  'time+fire': { result: 'Eternity', emoji: '♾️' },
  'earth+time': { result: 'History', emoji: '📜' },
  'time+human': { result: 'Philosopher', emoji: '🤔' },
  'time+stone': { result: 'Fossil', emoji: '🦕' },
  'time+life': { result: 'Death', emoji: '💀' },
  'time+time': { result: 'Infinity', emoji: '♾️' },
  'darkness+fire': { result: 'Shadow', emoji: '🌑' },
  'darkness+earth': { result: 'Cave', emoji: '🕳️' },
  'darkness+human': { result: 'Shadow', emoji: '👤' },
  'light+darkness': { result: 'Balance', emoji: '☯️' },
  'earth+light': { result: 'Dawn', emoji: '🌅' },
  'light+human': { result: 'Enlightenment', emoji: '✨' },
  'river+earth': { result: 'Canyon', emoji: '🏜️' },
  'river+stone': { result: 'Waterfall', emoji: '💧' },
  'river+mountain': { result: 'Waterfall', emoji: '💧' },
  'music+fire': { result: 'Rock', emoji: '🎸' },
  'music+wind': { result: 'Flute', emoji: '🎶' },
  'music+lightning': { result: 'Electric Guitar', emoji: '🎸' },
  'music+magic': { result: 'Spell Song', emoji: '🎵' },
  'death+fire': { result: 'Hell', emoji: '😈' },
  'death+water': { result: 'River Styx', emoji: '🌊' },
  'death+wind': { result: 'Ghost', emoji: '👻' },
  'death+human': { result: 'Undead', emoji: '🧟' },
  'death+magic': { result: 'Necromancy', emoji: '💀' },
  'death+life': { result: 'Rebirth', emoji: '✨' },
  'ghost+fire': { result: 'Will-o-Wisp', emoji: '👻' },
  'ghost+human': { result: 'Haunting', emoji: '👻' },
  'ghost+magic': { result: 'Exorcism', emoji: '✝️' },
  'wolf+moon': { result: 'Werewolf', emoji: '🌕' },
  'wolf+wolf': { result: 'Pack', emoji: '🐺' },
  'whale+fire': { result: 'Leviathan', emoji: '🐋' },
  'shark+magic': { result: 'Megalodon', emoji: '🦈' },
  'smoke+cloud': { result: 'Pollution', emoji: '🌁' },
  'pollution+rain': { result: 'Acid Rain', emoji: '☔' },
  'mushroom+magic': { result: 'Fairy Ring', emoji: '🍄' },
  'mushroom+life': { result: 'Mycelium', emoji: '🍄' },
  'sword+fire': { result: 'Flaming Sword', emoji: '⚔️' },
  'sword+magic': { result: 'Enchanted Blade', emoji: '⚔️' },
  'sword+ice': { result: 'Ice Sword', emoji: '❄️' },
  'armor+magic': { result: 'Enchanted Armor', emoji: '🛡️' },
  'society+fire': { result: 'Revolution', emoji: '🔥' },
  'earth+society': { result: 'Civilization', emoji: '🏛️' },
  'society+metal': { result: 'Industrial Revolution', emoji: '🏭' },
  'civilization+fire': { result: 'War', emoji: '⚔️' },
  'earth+civilization': { result: 'History', emoji: '📜' },
  'civilization+metal': { result: 'Industrialization', emoji: '🏭' },
  'civilization+magic': { result: 'Mythology', emoji: '📜' },
  'potion+life': { result: 'Elixir', emoji: '⚗️' },
  'potion+death': { result: 'Poison', emoji: '☠️' },
  'potion+magic': { result: "Philosopher's Stone", emoji: '🔮' },
  'magnet+metal': { result: 'Electric Motor', emoji: '⚙️' },
  'magnet+water': { result: 'Compass', emoji: '🧭' },
  'lens+glass': { result: 'Microscope', emoji: '🔬' },
  'telescope+star': { result: 'Astronomy', emoji: '🔭' },
  'phoenix+fire': { result: 'Immortality', emoji: '✨' },
  'phoenix+water': { result: 'Mist', emoji: '🌫️' },
  'earth+fossil': { result: 'Archaeology', emoji: '🦴' },
  'fossil+fire': { result: 'Oil', emoji: '🛢️' },
};

export function getCombination(a: string, b: string): { result: string; emoji: string } | null {
  const key = makeKey(a, b);
  return COMBINATIONS[key] ?? null;
}
